apiVersion: v1
kind: Service
metadata:
  name: endpoints
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: endpoints
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000